public enum State {
    WALKING_TO_BANK,
    USE_BANK,
    BANKING,
    WALKING_TO_MINOTAURS,
    POTTING,
    EATING,
    LOOKING_FOR_NPC,
    LOOTING_IN_COMBAT,
    EATING_IN_COMBAT,
    BURYING_IN_COMBAT,

}
